server:
  port: 3344


hystrix:
  config:
    stream:
      maxConcurrentConnections: 20
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 200

logging:
  level:
    org:
      apache:
        coyote: WARN