version: "3"
services:
  web-service:
    build: ./web-service
    ports:
      - 80:3344
    image: alexsimons/hystrix-example

#Use this compose file to run both the vertx web server and the
#Mongo database used for data persistence.
