version: "3"
services:
  web-service:
    build: ./web-service
    ports:
      - 80:3344
    image: alexsimons/hystrix-web-service:1.0.4

#Use this compose file to run both the spring boot web server