version: "3"
services:
  web-service:
    build: ./web-service
    ports:
      - 443:3344
    image: alexsimons/hystrix-web-service:1.1.2

#Use this compose file to run both the spring boot web server